name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger when code is pushed to the main branch
  pull_request:
    branches:
      - master  # Run checks on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world:latest .

      # Push the Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
